### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by mtechtruc** [NaamloosDT/DSharpPlus#44]
This part of the code is giving me an error exception
if (!e.Channel.IsPrivate)
 {
if(client.Guilds[e.Guild.ID].Members.Find(x => x.User.ID == e.Message.Author.ID).Roles.Contains(248495023132246017)) 
{
do stuff here
}
}

![oz5wrql](https://cloud.githubusercontent.com/assets/6856997/24099338/d8ff8602-0d2b-11e7-8ff6-bb8a5d9c9727.png)

**Comment by Emzi0767** [comment]
This looks like it fails from an `async void`. You should avoid doing that if possible.

Otherwise, you seem to be trying to access a guild that is not yet available.

**Comment by mtechtruc** [comment]
I rewrote it to make sure it doesn't fail from an async void but how would I change this so I can check the person's role?

**Comment by Emzi0767** [comment]
Well you're doing couple things wrong.

1. You have a guild (`guild`), why try to retrieve it again?
2. Use `.FirstOrDefault()` instead of `.Find()`.
3. Assign the result to something and nullcheck it first. There's a good chance it fails there for one reason or another. This might be due to incomplete user cache. To solve that, use `.GetAllMembers()` or `.GetMember(id)`.

**Comment by mtechtruc** [comment]
Thank you! With those suggestions, it stops crashing
